In [2]:
import numpy as np
print(np.__version__)

1.24.3


In [3]:
l = [1,2,3,4,5,6,7,8,9]
x = np.array(l)
print(x)
print(type(x))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [4]:
print(x+5)
print(x-5)
print(x*5)
print(x/5)

[ 6  7  8  9 10 11 12 13 14]
[-4 -3 -2 -1  0  1  2  3  4]
[ 5 10 15 20 25 30 35 40 45]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


In [5]:
# must have equal no of items in both the numpy array

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a+b
print(c)

[ 7  9 11 13 15]


In [7]:
a = np.array([1,2,3,4,5])
print(a.shape)
# a.shape

(5,)


In [11]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print(a.shape)

# in output it means 2 rows, 5 columns i.e
# columnns no. & its data must be same in both row as like in matrix

(2, 5)


In [13]:
# 3D data

a = np.array([[[1,2,3],[4,5,0]],
              [[6,7,8],[9,10,0]]])
print(a.shape)

(2, 2, 3)


In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [18]:
np.ones((3,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [19]:
# identity matrix

np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# shaping

In [20]:
a = np.array([[1,2,3],
             [4,5,6]])
print(a.shape)
print(a.reshape(3,2))
print(a.reshape(1,6))
print(a.reshape(3,2))
print(a.reshape(6,1))

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# horizontal & vertical stacking

In [21]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[1,2,3],
             [4,5,6]])
c = a+b
c

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [22]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[11,22,33],
             [44,55,66]])
np.hstack((a,b))

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

In [23]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[11,22,33],
             [44,55,66]])
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33],
       [44, 55, 66]])

In [27]:
a = np.array([1,2,3])
b = np.array([11,22,33])
np.vstack((a,b))

array([[ 1,  2,  3],
       [11, 22, 33]])

In [28]:
a = np.array([1,2,3])
b = np.array([11,22,33,34])
np.hstack((a,b))

array([ 1,  2,  3, 11, 22, 33, 34])

# generate random numbers

In [30]:
print(np.random.rand(2,2))

[[0.71415319 0.15944982]
 [0.42097658 0.81212561]]


In [31]:
print(np.random.rand(5,5))

[[0.18980385 0.5828834  0.9344476  0.63465256 0.45057873]
 [0.11047705 0.7553996  0.15633454 0.47866881 0.01075729]
 [0.96708286 0.65951135 0.15474877 0.73998827 0.30477261]
 [0.47349276 0.88895701 0.24486393 0.39974948 0.21663862]
 [0.08804707 0.26598699 0.08101071 0.37742213 0.61809959]]


In [36]:
print(np.random.randint(0,10, size=[5,5]))

[[1 0 1 2 6]
 [1 4 3 1 7]
 [2 1 5 6 3]
 [6 2 9 2 2]
 [1 5 0 0 2]]


In [39]:
print(np.random.choice(['a','e','i','o','u'], size=10))

['e' 'i' 'e' 'o' 'e' 'u' 'e' 'o' 'i' 'o']


In [38]:
print(np.random.choice(['a','e','i','o','u'], size=[10,4]))

[['e' 'i' 'e' 'a']
 ['e' 'u' 'i' 'a']
 ['i' 'u' 'i' 'u']
 ['o' 'u' 'u' 'a']
 ['o' 'u' 'u' 'i']
 ['u' 'e' 'i' 'a']
 ['u' 'i' 'o' 'e']
 ['a' 'i' 'a' 'u']
 ['a' 'u' 'o' 'i']
 ['u' 'a' 'i' 'o']]


In [42]:
# adding probability to randomness

print(np.random.choice(['a','e','i','o','u'], size=10, p=[0.3,0.1,0.1,0.4,0.1]))

['e' 'e' 'o' 'a' 'i' 'a' 'o' 'u' 'a' 'o']


In [43]:
# no concatenation on string

print(np.random.choice(['a','e','i','o','u'], size=[10,4])) + 'a'


[['a' 'a' 'e' 'o']
 ['o' 'u' 'i' 'u']
 ['a' 'a' 'u' 'a']
 ['u' 'a' 'o' 'e']
 ['u' 'e' 'e' 'o']
 ['i' 'e' 'e' 'o']
 ['o' 'e' 'u' 'o']
 ['i' 'u' 'u' 'e']
 ['a' 'e' 'u' 'o']
 ['o' 'o' 'i' 'u']]


TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

In [5]:
import numpy as np
print(np.random.randint(0,10, size=[5,5]) + 1)

[[ 7  8  5  7  4]
 [ 4  8  8 10  1]
 [ 3  9  5  8  9]
 [ 1  6  3  1  9]
 [ 3  9  2  5  8]]


# min,max,mean, standard deviation

In [3]:
import numpy as np

a = np.array([132,34,546,245,5,223,679])
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))

5
679
266.2857142857143
236.3893364078569


# determinant - det()

In [5]:
import scipy.linalg as slin
import numpy as np

a = np.array([[ 3, -5, 8],
              [-1, 2, 3],
              [-5, -6, 2]])
slin.det(a)

259.0

# trace of the matrix - trace()

In [6]:
# trace = adding the diagonal elements of the matrix --trace()

import numpy as np

a = np.array([[ 3, -5, 8],
              [-1, 2, 3],
              [-5, -6, 2]])
np.trace(a)

7

# inverse of the matrix - inv()

In [7]:
import scipy.linalg as slin
import numpy as np

a = np.array([[ 3, -5, 8],
              [-1, 2, 3],
              [-5, -6, 2]])
slin.inv(a)

array([[ 0.08494208, -0.14671815, -0.11969112],
       [-0.05019305,  0.17760618, -0.06563707],
       [ 0.06177606,  0.16602317,  0.003861  ]])

# transpose of the matrix - transpose()

In [11]:
import numpy as np

a = np.array([[ 3, -5, 8],
              [-1, 2, 3],
              [-5, -6, 2]])

np.transpose(a)

array([[ 3, -1, -5],
       [-5,  2, -6],
       [ 8,  3,  2]])

# matrix multiplication

In [14]:
# must use np.matrix instead of np.array for matrix multiplication

import numpy as np

a = np.matrix([[ 3, -5, 8],
              [-1, 2, 3],
              [-5, -6, 2]])

b = np.matrix([[3],
              [4],
              [1]])

a*b

matrix([[ -3],
        [  8],
        [-37]])